import '~/styles/globals.css'

import { Inter, Lexend } from 'next/font/google'

import { TRPCReactProvider } from '~/trpc/react'
import clsx from 'clsx'

export const metadata = {
  title: 'Flavor UI - Flutter UI Components & Templates',
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: '/flavorui-favicon.svg' }],
}

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
})

const lexend = Lexend({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-lexend',
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html
      lang="en"
      className={clsx(
        'h-full scroll-smooth bg-white antialiased',
        inter.variable,
        lexend.variable,
      )}
    >
      <body className="flex h-full flex-col">
        <TRPCReactProvider>{children}</TRPCReactProvider>
      </body>
    </html>
  )
}
